# Generated by Django 4.0.6 on 2022-07-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='documents',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='site@site.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
